export const CHANGE_INPUT_URL = "CHANGE_INPUT_URL";
export const UPDATE_FACE_BOXES = "UPDATE_FACE_BOXES";
export const RESET_APP = "RESET_APP";
export const CHANGE_ROUTE = "CHANGE ROUTE";
export const CHANGE_SIGNED_IN_STATUS = "SIGNED_IN_STATUS";
export const UPDATE_USER = "UPDATE_USER";